flowchart TD
    A["Måla innertaket"] --> B["Lerkilna"]
    B --> C["Installera kamin och tankar"]
    D1["köpa skorsten"] --> E1["Installera skorsten"]
    D2["köpa kulvert"] --> E2["Installera kulvert"]
    E2 --> F2["Pannrum"]
    D3["Pumpa vatten 4-5 veckor"] --> E3["Gör vattentest"]
    E3 --> F3["Köpa vattenfilter?"]
    E4["Installera skorsten"] --> F4["Mura kamin"]
    F4 --> G4["Lerkilna kamin"]
    G["Slutbesked"] --> H["Flytta in!!!"]
    H --> I1["Stora altanen"] & I2["Olja loftgolvet"] & I3["Bygga batterihus"] & I4["Köpa tvättmaskin"] & I5["Entrealtanen"] & I6["Köpa fönsterbleck"] & I7["Lister"]
    I1 --> J1["Huset klart"]
    I2 --> J2["Pump hus"]
    I3 --> J3["Vinterträdgården"]
    J1 --> K["Byggprojekt klart"] & K
    J2 --> K
    J3 --> K
    I4 --> J1
    I5 --> J1
    I6 --> J1
    I7 --> J1
    E7["Installera fläkt"] --> G
    G4 --> G
    F3 --> G
    F2 --> G
    E1 --> F2
    C --> F2
    E6["Gör ler golvet"] --> D5["Snickra kök"]
    D5 --> E7
